#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
xset +fp /usr/share/fonts/local
xset +dpms
xset dpms 0 0 300
xrandr --output DVI-1 --primary
xrandr --output DVI-1 --mode 1920x1200
redshiftgui -n &
urxvtd -q -o -f

~/.fehbg
~/.dotfiles/_bin/dzconky
mpd ~/.mpdconf

exec dbus-launch xmonad
