#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
xset +fp /usr/share/fonts/local

urxvtd -q -o -f
~/.fehbg
udiskie &
mpd ~/.mpd/mpd.conf

while true; do
    xsetroot -name "$(date +"%A %d %B %I:%M%p")"
    sleep 1
done &

exec dwm
